# Google Cloud Build - Staging Environment
# Triggered by: main branch
# Deploys to: sqlgym-staging on Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - '$_ARTIFACT_REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/sqlgym-staging:$COMMIT_SHA'
      - '-t'
      - '$_ARTIFACT_REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/sqlgym-staging:latest'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '$_ARTIFACT_REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/sqlgym-staging'

  # Deploy to Cloud Run - Staging
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sqlgym-staging'
      - '--image=$_ARTIFACT_REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/sqlgym-staging:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=$_MEMORY'
      - '--cpu=$_CPU'
      - '--timeout=$_TIMEOUT'
      - '--max-instances=$_MAX_INSTANCES'
      - '--min-instances=$_MIN_INSTANCES'
      - '--concurrency=$_CONCURRENCY'
      - '--set-env-vars=ENV=staging'
      - '--update-secrets=DATABASE_URL=staging-database-url:latest,JWT_SECRET=staging-jwt-secret:latest,ADMIN_SECRET_KEY=staging-admin-secret:latest,REDIS_URL=staging-redis-url:latest'

images:
  - '$_ARTIFACT_REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/sqlgym-staging:latest'
  - '$_ARTIFACT_REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/sqlgym-staging:$COMMIT_SHA'

# Substitution variables for staging
substitutions:
  _ARTIFACT_REGISTRY_LOCATION: 'us-central1'
  _ARTIFACT_REGISTRY_REPO: 'sqlgym'
  _REGION: 'us-central1'
  _MEMORY: '1Gi'
  _CPU: '1'
  _TIMEOUT: '300'
  _MAX_INSTANCES: '5'
  _MIN_INSTANCES: '0'
  _CONCURRENCY: '80'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
