/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-logos.js
 * Run 'npm run generate:logos' to regenerate
 */

import teslaLogo from '@assets/logos/Tesla.svg';
import airbnbLogo from '@assets/logos/airbnb.svg';
import amazonLogo from '@assets/logos/amazon.svg';
import appleLogo from '@assets/logos/apple.svg';
import googleLogo from '@assets/logos/google.svg';
import mcdonaldLogo from '@assets/logos/mcdonald.svg';
import metaLogo from '@assets/logos/meta.svg';
import microsoftLogo from '@assets/logos/microsoft.svg';
import netflixLogo from '@assets/logos/netflix.svg';
import snapchatLogo from '@assets/logos/snapchat.svg';
import stripeLogo from '@assets/logos/stripe.svg';

export interface CompanyInfo {
  id: string;
  name: string;
  displayName: string;
  logoPath: string;
  primaryColor: string;
  secondaryColor?: string;
}

// Auto-generated logo registry
const LOGO_REGISTRY: Record<string, string> = {
  tesla: teslaLogo,
  airbnb: airbnbLogo,
  amazon: amazonLogo,
  apple: appleLogo,
  google: googleLogo,
  mcdonald: mcdonaldLogo,
  meta: metaLogo,
  microsoft: microsoftLogo,
  netflix: netflixLogo,
  snapchat: snapchatLogo,
  stripe: stripeLogo,
};

// Default color configurations for known companies
const COMPANY_COLORS: Record<string, Pick<CompanyInfo, 'primaryColor' | 'secondaryColor'>> = {
  microsoft: {
    primaryColor: "#00BCF2",
    secondaryColor: "#0078D4"
  },
  google: {
    primaryColor: "#4285F4",
    secondaryColor: "#DB4437"
  },
  apple: {
    primaryColor: "#000000",
    secondaryColor: "#A8A8A8"
  },
  amazon: {
    primaryColor: "#FF9900",
    secondaryColor: "#232F3E"
  },
  meta: {
    primaryColor: "#1877F2",
    secondaryColor: "#42B883"
  },
  netflix: {
    primaryColor: "#E50914",
    secondaryColor: "#221F1F"
  },
  stripe: {
    primaryColor: "#635BFF",
    secondaryColor: "#0A2540"
  },
  airbnb: {
    primaryColor: "#FF5A5F",
    secondaryColor: "#FF385C"
  },
  tesla: {
    primaryColor: "#CC0000",
    secondaryColor: "#000000"
  },
  uber: {
    primaryColor: "#000000",
    secondaryColor: "#1FBAD6"
  },
  shopify: {
    primaryColor: "#7AB55C",
    secondaryColor: "#95BF47"
  },
  discord: {
    primaryColor: "#5865F2",
    secondaryColor: "#7289DA"
  },
  slack: {
    primaryColor: "#4A154B",
    secondaryColor: "#36C5F0"
  },
  snapchat: {
    primaryColor: "#FFFC00",
    secondaryColor: "#000000"
  },
  mcdonald: {
    primaryColor: "#FFC72C",
    secondaryColor: "#DA291C"
  }
};

/**
 * Normalizes company name to match expected filename format
 */
function normalizeCompanyName(name: string): string {
  return name
    .replace(/[,_-]/g, '')
    .replace(/\s+/g, '')
    .toLowerCase();
}

/**
 * Retrieves company logo information by name
 */
export function getCompanyLogo(companyName: string): CompanyInfo | null {
  const normalized = normalizeCompanyName(companyName);
  const logoPath = LOGO_REGISTRY[normalized];
  
  if (!logoPath) {
    return null;
  }

  const colors = COMPANY_COLORS[normalized] || {
    primaryColor: '#000000',
    secondaryColor: '#666666',
  };

  return {
    id: normalized,
    name: normalized,
    displayName: companyName,
    logoPath,
    ...colors,
  };
}

/**
 * Returns all available company logos
 */
export function getAllCompanyLogos(): CompanyInfo[] {
  return Object.keys(LOGO_REGISTRY).map(key => ({
    id: key,
    name: key,
    displayName: key.charAt(0).toUpperCase() + key.slice(1),
    logoPath: LOGO_REGISTRY[key],
    ...(COMPANY_COLORS[key] || {
      primaryColor: '#000000',
      secondaryColor: '#666666',
    }),
  }));
}

export { LOGO_REGISTRY, COMPANY_COLORS };
